### ISSUE TITLE
Не копировать исходники проекта в базовый образ

### ISSUE THREAD

**Issue by Znack** [fullstack-development/haskell-starter-kit#22]
Сейчас на нашем проекте столкнулись с неочевидной багой. У нас есть базовый образ в котором мы компилим зависимости, чтобы потом долго не ждать. Ожнако если из проекта удалить файл, но не пересобрать базовый образ, то этот файл останется в базовом образе и докер контейнеры будут пытаться собрать с ним же и будут фейлиться (если не компиляется утсаревший файл этот). Но базовый контейнер по своей задумке должен пересобираться редко, только когда изменились зависимости, тут же надо в голове держать постоянно, что надо его ещё пересобирать после каждого удаления файла. 

В итоге решение такое должно быть, что в базовом образе вообще файлов с исходниками быть не должно

**Comment by Znack** [comment]
@stanislav-az обрати внимание, на что напоролись в проекте :)

**Comment by Znack** [comment]
@antonkalinin-ml можно ещё вот над этой задачкой интересной подумать :)

**Comment by antonkalinin-ml** [comment]
Можно удалять все исходники в базовом образе после сборки зависимостей. Можно в производном образе удалять исходники перед копированием новых, чтобы старых не оставалось. Я бы сделал и то, и другое, чтобы вам базовый образ не ребилдить лишний раз.

**Comment by Znack** [comment]
Ну либо посмотреть как можно элегантно заменить `COPY ./ haskell-starter-kit/` чтобы он не копировал всё-всё, а оставлял папку `src` :)

**Comment by antonkalinin-ml** [comment]
Чтобы `stack build --only-dependencies` сработал, должны присутствовать каталоги `src`, `app`, `test` (все пустые) и файлы `stack.yaml`, `stack.yaml.lock`, `package.yaml`, `ChangeLog.md` и `README.md` - последние два, потому что упомянуты в package.yaml. Без этого он не сформирует cabal-файл, ему надо прочитать все каталоги с исходниками.

Можно не копировать все, а создавать только нужные каталоги, но это ставит Dockerfile.deps в зависимость от содержимого package.yaml. Раз в год кто-нибудь заведет новую папку, докерфайл забудут обновить, придется терять время на разбирательства, почему не работает. Я бы лучше оставил копирование исходников в базовый образ как есть - это лишние пару секунд, ничто по сравнению с временем сборки зависимостей, зато надежно. В конце сборки зависимостей очистим папку и нормально.

**Comment by Znack** [comment]
Хм, в целом да, звучит разумно. Да, давай просто после сборки и правда чистить папку src да и всё — дешёво и сердито :)

**Comment by antonkalinin-ml** [comment]
Вот бы сделать так, чтобы stack сначала загружал базу пакетов, до копирования исходников и запуска stack setup. Большая часть времени при построении deps-образа уходит на базу пакетов и загрузку ghc, одну и ту же работу. База пакетов же не зависит от снапшота? Когда я компилил другой проект с другим снапшотом и версией ghc, он не скачивал базу снова. Докер кеширует часть шагов, но все, что идет после копирования, он не кеширует - видимо, скопированные файлы всегда отличаются.

**Comment by antonkalinin-ml** [comment]
Открыл ревью https://github.com/fullstack-development/haskell-starter-kit/pull/23 .

На будущее можно подумать на тему, как избежать копирования того, что точно не понадобится. Сейчас копируется и папка .git, которая со временем сильно вырастет, и .stack-work (хотя это вряд ли - сервер в докере запускает только фронтенд, у них нет стека локально). Мы могли бы копировать только те файлы, которые есть в гите, при помощи git archive, плюс выбранные локальные конфиги, 3 штуки (а в будущем меньше, если удастся их генерировать при помощи Dhall или скриптов). Безопасный вариант - перед запуском докера создавать скриптом папку, куда копировать все, кроме .git и .stack-work, и эту папку будет забирать докер.

Думаю, нужен скрипт для развертывания проекта - скопировать те же конфиги. Они не требуют правки, проект можно протестировать и так. Правки понадобятся на проде. Это поможет копированию в докер - скрипт можно будет запускать в контейнере, и все конфиги создадутся с рабочей, дефолтной конфигурацией.

> Вот бы сделать так, чтобы stack сначала загружал базу пакетов, до копирования исходников и запуска stack setup. 

`stack update` делает то, что надо :). Снапшот и проект не нужны.

**Comment by stanislav-az** [comment]
> как избежать копирования того, что точно не понадобится

есть же файл `.dockerignore` , то что в нем не будет копироваться, там уже есть `.stack-work` , можно добавить` .git`

**Comment by antonkalinin-ml** [comment]
stack дружит с докером: https://docs.haskellstack.org/en/stable/docker_integration/ .
Для каждого снапшота есть свой образ с предустановленным ghc, и вроде как даже есть образы с предварительно собранными либами в стекедже. Каталог проекта и ~/.stack монтируются внутрь образа, поэтому ничего копировать не надо и результаты билда не теряются. Однако это требует установки стека локально. Без стека на машине мало что можно сделать для экономии времени билда - для начала, чтобы скачать правильный образ с нужным ghc и либами, нужно распарсить stack.yaml. Если бы на машины фронтендеров можно было ставить стек, проблем было бы меньше :).

**Comment by stanislav-az** [comment]
> stack дружит с докером: https://docs.haskellstack.org/en/stable/docker_integration/ .

я пытался это использовать, очень большой образ, обновляется редко, так что там будет даунгрейд lts
использовать не очень удобно, так как все команды `stack ...` теперь после этого изменяются, чтобы учитывать одну строчку в конфиге стека, делают дополнительную работу связанную с образом. это не очень удобно для разработки бекенда

**Comment by stanislav-az** [comment]
могут быть еще дополнительные проблемы по настройке образа, так как мы будем использовать существующую систему, это дает меньше свободы, я использовал вот этот гайд https://www.fpcomplete.com/blog/2017/12/building-haskell-apps-with-docker/ , если хочешь попробовать настроить (но это не так хорошо работает как оказалось)

**Comment by antonkalinin-ml** [comment]
> > как избежать копирования того, что точно не понадобится
> 
> есть же файл `.dockerignore` , то что в нем не будет копироваться, там уже есть `.stack-work` , можно добавить` .git`

Здорово, это самый простой вариант.

Кстати, заметил, что stack.yaml.lock заигнорен в .gitignore и .dockerignore. Локфайлы нельзя игнорить, они важны для воспроизводимости билда и должны быть в системе контроля версий: https://docs.haskellstack.org/en/stable/lock_files/#lock-files . Если не возражаете, я его добавлю в гит и уберу из игнора.

**Comment by stanislav-az** [comment]
> Если не возражаете, я его добавлю в гит и уберу из игора

Не знаю, нам в нашем случае же не нужна воспроизводимость билда так сильно? 
Мы его убирали так как он генерируется на основе других файлов, и чтобы мерж конфликты не решать.

**Comment by stanislav-az** [comment]
Лучше уж на `nix` перейти для обеспечения воспроизводимости билда

**Comment by antonkalinin-ml** [comment]
> > Если не возражаете, я его добавлю в гит и уберу из игора
> 
> Не знаю, нам в нашем случае же не нужна воспроизводимость билда так сильно?
> Мы его убирали так как он генерируется на основе других файлов, и чтобы мерж конфликты не решать.

Конкретно в стартерките воспроизводимый билд, может быть, не нужен, но он понадобится в производном проекте. У двух людей могут сбилдиться разные версии приложения, с разными либами, будет необъяснимо разное поведение, производительность, разные невоспроизводимые баги и ошибки сборки, на которые надо тратить уйму времени.

Локфайл генерируется на основе хешей всех используемых либ и фиксирует точные версии, может даже спеки. Он не меняется, если вы не меняете перечень либ или снапшот. Соответственно, мержконфликты возникают, только когда двое людей в разных ветках изменили перечень или версию либ. Локфайл содержит хеши для внешних либ не из снапшота и для самого снапшота, т.е. если конфликт относится к разным либам, он легко разрешается. Если же двое человек одновременно добавили одну либу или исправили версию, то надо решить, какую из этих версий использовать, _и зафиксировать ее в локфайле_, пусть даже удалением и регенерацией локфайла, но зато она будет зафиксирована в репозитории и далее у всех будет одинаковый билд. Я как-то не вижу здесь сложностей с мержами. Мержил похожие локфайлы пакетного менеджера в iOS - конечно, не совсем то, но концепция и формат похожи, больших проблем не было.

> Лучше уж на nix перейти для обеспечения воспроизводимости билда

Мои познания никса ограничены только названием, быстро я вам его не запилю :). Разыигнорить stack.yaml.lock быстрее и эффективнее.

**Comment by antonkalinin-ml** [comment]
У меня вот такой локфайл:

```
# This file was autogenerated by Stack.
# You should not edit this file by hand.
# For more information, please see the documentation at:
#   https://docs.haskellstack.org/en/stable/lock_files

packages:
- completed:
    hackage: servant-options-0.1.0.0@sha256:39f50166a68006250e79370372f553ca476f14d06d93fa0c401050253aeba803,914
    pantry-tree:
      size: 293
      sha256: 7812baf1b27c62068ba634207fbd7077b886424d666b36739a78c6d4008a1fd4
  original:
    hackage: servant-options-0.1.0.0
- completed:
    hackage: servant-auth-0.4.0.0@sha256:01d02dfb7df4747fc96442517146d7d4ab0e575e597a124e238e8763036ea4ff,2125
    pantry-tree:
      size: 332
      sha256: a7ec2c54fddfa417ee2467f1131b1d83ad43cc29ddfd4b98869fc924e4b5e980
  original:
    hackage: servant-auth-0.4.0.0
- completed:
    hackage: servant-auth-server-0.4.6.0@sha256:b411b44f4252e91e5da2455d71a7113c8b5b8ff2d943d19b2ddedcfcf0392351,5111
    pantry-tree:
      size: 1376
      sha256: 8cd29612112546a02085e2cb30dd5a72ea46ed81e644195c589d0b26652279cb
  original:
    hackage: servant-auth-server-0.4.6.0
snapshots:
- completed:
    size: 565266
    url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/17/5.yaml
    sha256: 78e8ebabf11406261abbc95b44f240acf71802630b368888f6d758de7fc3a2f7
  original: lts-17.5
```

Тут даже не все либы, а только extra-deps, которые меняются еще реже (в проекте всего три штуки таких). Либы, входящие в снапшот, зафиксированы хешем снапшота.
